#! /usr/bin/env bash

source "$( dirname "$0" )/dot-bashrc.d/commonlib"

src="$( realpath "$( dirname "$( realpath "$0" )" )" )"
dst="$( realpath . )"

if [ "$src" '=' "$dst" ] ; then
    echo "error: cannot run $0 from within its own directory" 1>&2
    exit 1
fi

cd "$src"
for path in * ; do
    tmp_dst="$dst/$path"
    if [ "${path:0:4}" '=' 'dot-' ] ; then
        tmp_dst="$tmp_dst/.${path:4}"
    fi

    rm -rf "$tmp_dst"
    cp -r "$path" "$tmp_dst"
done

