#! /usr/bin/env bash

if [ -z "$__aliases_guard" ] ; then __aliases_guard=1
source "$HOME/.bash-lib/init"

mload commonlib
mload introspection

if env_check TRUE INTROSPECT_LS_COLOR_SUPPORT ; then
    alias ls="ls -F --color=auto"
else
    alias ls="ls -GF"
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias vi='vim'

fi #!__aliases_guard

