#! /usr/bin/env bash

if [ -z "$__autoload_guard" ] ; then __autoload_guard=1
source "$HOME/.bash-lib/init"

_old_ifs="$IFS"
IFS=':'

for module in $AUTOLOAD ; do
    mload "$module"
done

IFS="$_old_ifs"
unset _old_ifs

fi #!__autoload_guard

