#! /usr/bin/env bash

if [ -z "$__commonlib_guard" ] ; then __commonlib_guard=1
source "$HOME/.bash-lib/init"

function envget() {
    while [ -n "$*" ] ; do
        local key="$1" ; shift
        eval 'echo $'"$key"
    done
}

function envset() {
    args=("$@")
    for ((i=0; i<${#args[@]}; i+=2)) ; do
        local key="${args[$i]}"
        local value="${args[$((i + 1))]}"
        eval "$key="'"'"$value"'"'
    done
}

function __env_check_internal() {
    mode="$1"
    invert="$2"
    var="$3"

    result=1
    if [ "$mode" '=' 'SET' ] ; then
        if eval '[ -n "${'"$var"'+set}" ]' ; then
            result=0
        fi
    elif [ "$mode" '=' 'EMPTY' ] ; then
        val="$( envget "$var" )"
        if [ -z "$val" ] ; then
            result=0
        fi
    elif [ "$mode" '=' 'ZERO' ] ; then
        val="$( envget "$var" )"
        if [ "$(( val == 0 ))" '==' '1' -a -n "$val" ] ; then
            result=0
        fi
    elif [ "$mode" '=' 'TRUE' ] ; then
        val="$( envget "$var" )"
        if [ "$(( val == 0 ))" '!=' '1' ] ; then
            result=0
        fi
    fi

    if [ "$invert" '=' '1' ] ; then
        result=$(( 1 - result ))
    fi

    echo "$result"
}

function env_check() {
    mode="$1" ; shift

    if [ "$mode" '!=' 'SET' -a \
         "$mode" '!=' 'UNSET' -a \
         "$mode" '!=' 'EMPTY' -a \
         "$mode" '!=' 'NONEMPTY' -a \
         "$mode" '!=' 'ZERO' -a \
         "$mode" '!=' 'NONZERO' -a \
         "$mode" '!=' 'TRUE' -a \
         "$mode" '!=' 'FALSE' ] ; then
        first_arg="$mode"
        mode="NONEMPTY"
    fi

    invert=0
    if [ "$mode" '=' 'UNSET' -o \
         "$mode" '=' 'NONEMPTY' -o \
         "$mode" '=' 'NONZERO' -o \
         "$mode" '=' 'FALSE' ] ; then
        invert=1
    fi

    if [ "$invert" '=' '1' ] ; then
        if [ "$mode" '=' 'UNSET' ] ; then
            mode="SET"
        elif [ "$mode" '=' 'NONEMPTY' ] ; then
            mode="EMPTY"
        elif [ "$mode" '=' 'NONZERO' ] ; then
            mode="ZERO"
        elif [ "$mode" '=' 'FALSE' ] ; then
            mode="TRUE"
        fi
    fi

    result=0
    if [ -n "$first_arg" ] ; then
        result="$( __env_check_internal "$mode" "$invert" "$first_arg" )"
        unset first_arg
    fi

    while [ "$#" '!=' '0' ] ; do
        if [ "$result" '=' '1' ] ; then
            break
        fi

        var="$1" ; shift
        result="$( __env_check_internal "$mode" "$invert" "$var" )"
    done

    return $result
}

function env_checkset() {
    args=("$@")
    for ((i=0; i<${#args[@]}; i+=2)) ; do
        local var="${args[$i]}"
        local value="${args[$((i + 1))]}"

        if env_check UNSET "$var" ; then
            envset "$var" "$value"
        fi
    done
}

function check_exit_code() {
    local result_var="$1" ; shift
    local result_code=

    eval "
        $@ &> /dev/null
        envset result_code \"\$?\"
        envset $result_var \"\$result_code\"
    "

    return $result_code
}

function check_output() {
    local result_var="$1" ; shift
    local result_code=

    eval "
        envset $result_var \"\$( $@ 2> /dev/null )\"
        envset result_code=\"\$?\"
    "

    return $result_code
}

function check_command() {
    local result_var="$1" ; shift
    local result_code_var="${result_var}_code"

    eval "
        envset $result_var \"\$( $@ 2> /dev/null )\"
        envset $result_code_var=\"\$?\"
    "

    return $result_code
}

function envappend() {
    local sep=':'

    local regex='[\.;:\\/, -]'
    if [[ "$1" =~ $regex ]] ; then
        sep="$1" ; shift
    fi

    local var="$1" ; shift
    local val="$1" ; shift

    args=("$@")
    for ((i=0; i<${#args[@]}; ++i)) ; do
        val="$val$sep${args[$i]}"
    done

    if env_check EMPTY "$var" ; then
        envset "$var" "$val"
    else
        envset "$var" "$( envget "$var" )$sep$val"
    fi
}

function envpush() {
    local sep=':'

    local regex='[\.;:\\/, -]'
    if [[ "$1" =~ $regex ]] ; then
        sep="$1" ; shift
    fi

    local var="$1" ; shift
    local val="$1" ; shift

    args=("$@")
    for ((i=0; i<${#args[@]}; ++i)) ; do
        val="${args[$i]}$sep$val"
    done

    if env_check EMPTY "$var" ; then
        envset "$var" "$val"
    else
        envset "$var" "$val$sep$( envget "$var" )"
    fi
}

realpath . &> /dev/null
if [ "$?" '!=' '0' ]; then
    function realpath() {
        python -c "$(
            echo 'import os.path as p'
            echo 'import sys'
            echo 'for arg in sys.argv[1:]:'
            echo '    print p.abspath(arg)'
        )" "$@"
    }
fi

function searchpath() {
    local path="$( envget $1 )" ; shift
    local file_glob="$1" ; shift

    ret_code=0

    while [ -n "$path" ] ; do
        local dir="${path/:*/}"
        local ndir="${#dir}"
        path="${path:$(( ndir + 1 ))}"

        if [ -d "$dir" ] ; then
            eval_line='find "$dir" -maxdepth 1 -iname $file_glob'

            if [ "$ret_code" '=' '0' ] ; then
                eval "$eval_line" | while read LINE ; do
                    echo "$LINE"
                    ret_code=1
                done
            else
                eval "$eval_line"
            fi
        fi
    done

    return "$ret_code"
}

function platform() {
    os="$1"
    if [ -z "$os" ] ; then os="$OSTYPE" ; fi

    case "$os" in
        linux*)   echo "LINUX"   ;;
        darwin*)  echo "MAC"     ;;
        msys*)    echo "WINDOWS" ;;
        solaris*) echo "SOLARIS" ;;
        bsd*)     echo "BSD"     ;;
        *)        echo "UNKNOWN" ;;
    esac
}

function push_path() {
    local path_var="$1" ; shift

    args=("$@")
    for ((i=0; i<${#args[@]}; ++i)) ; do
        dir="${args[$i]}"
        if [ -d "$dir" ] ; then
            envpush $path_var "$dir"
        fi
    done
}

function push_install() {
    args=("$@")
    for ((i=0; i<${#args[@]}; ++i)) ; do
        dir="$( realpath "${args[$i]}" )"

        push_path PATH               "$dir/bin"
        push_path PATH               "$dir/sbin"
        push_path C_INCLUDE_PATH     "$dir/include"
        push_path CPLUS_INCLUDE_PATH "$dir/include"

        push_path LD_LIBRARY_PATH    "$dir/lib"
        push_path LD_LIBRARY_PATH    "$dir/lib32"
        push_path LD_LIBRARY_PATH    "$dir/lib64"

        push_path LD_RUN_PATH        "$dir/lib"
        push_path LD_RUN_PATH        "$dir/lib32"
        push_path LD_RUN_PATH        "$dir/lib64"

        if [ "$INTROSPECT_PLATFORM" '=' 'MAC' ] ; then
            push_path DYLD_RUN_PATH  "$dir/lib"
            push_path DYLD_RUN_PATH  "$dir/lib32"
            push_path DYLD_RUN_PATH  "$dir/lib64"
        fi

        push_path NODE_PATH           "$dir/lib/node_modules"
    done
}

function ppid() {
    args=("$@")
    for ((i=0; i<${#args[@]}; ++i)) ; do
        local pid="${args[$i]}"
        if [ -z "$pid" ] ; then
            pid="$$"
        fi

        local line="$( ps -ef | awk "\$2==$pid{print}" )"
        local result='x'
        if [ -n "$line" ] ; then
            result="$( echo "$line" | awk '{print $3}' )"
        fi

        echo "$result"
    done
}

function pid_walk() {
    local pid="$1"
    if [ -z "$pid" ] ; then
        pid="$$"
    fi

    while [ -n "$pid" -a "$pid" '!=' 'x' ] ; do
        echo "$pid"
        pid="$( ppid "$pid" )"
    done
}

mload introspection

fi #!__commonlib_guard

