#! /usr/bin/env bash

if [ -z "$__introspection_guard" ] ; then __introspection_guard=1
source "$HOME/.bash-lib/init"

mload commonlib

check_exit_code INTROSPECT_LS_COLOR_SUPPORT ls --color
INTROSPECT_LS_COLOR_SUPPORT="$(( INTROSPECT_LS_COLOR_SUPPORT == 0 ))"

INTROSPECT_PLATFORM="$( platform )"

fi #!__introspection_guard

