#! /usr/bin/env bash

GIT_DIR=".git"

if [ -f "$GIT_DIR" ] ; then
    GIT_DIR="$( cat "$GIT_DIR" | grep 'gitdir:' | sed -re 's/gitdir\: //g' )"
fi

while [ -d "$GIT_DIR/rebase-merge" -o -d "$GIT_DIR/rebase-apply" ] ; do
    (
        git -c color.ui=always --no-pager log --oneline HEAD^..
        git -c color.ui=always --no-pager diff HEAD^ HEAD
    ) | less -RSX

    echo -n "commit message: "
    read message
    if [ -n "$message" ] ; then
        git commit --amend -m "$message"
    fi

    git rebase --continue
done

