#! /usr/bin/env bash

if [ -z "$__bashrc_guard" ] ; then __bashrc_guard=1
source "$HOME/.bash-lib/init"

mload autoload

mload aliases
mload commonlib
mload completion
mload disable_ixon
mload docker_machine
mload environment
mload force_us_utf8_locale
mload gpg_agent
mload introspection
mload local_rc_file
mload mac_coreutils
# mload prompt
mload tab_complete
mload solarize

mload pwnall

fi # !__bashrc_guard

