#! /usr/bin/env bash

mload introspection

if [ "$INTROSPECT_PLATFORM" = 'MAC' ] ; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        source $(brew --prefix)/etc/bash_completion
    fi
fi
