#! /usr/bin/env bash

if [ -z "$__completions_guard" ] ; then __completions_guard=1

mload introspection

if [ "$INTROSPECT_PLATFORM" = 'MAC' ] ; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        source $(brew --prefix)/etc/bash_completion
    fi
fi

fi # !__completions_guard

