#! /usr/bin/env bash

if [ -z "$__docker_machine_guard" ] ; then __docker_machine_guard=1

mload commonlib

if [ "$INTROSPECT_PLATFORM" = 'MAC' ] ; then
    if check_exit_code _ which docker-machine ; then
        eval "$( docker-machine env default )"
    fi
fi

fi # !__docker_machine_guard

