#! /usr/bin/env bash

export NVM_DIR="$HOME/.nvm"

if [ '!' -d "$NVM_DIR" ] ; then
    __nvm_url="https://raw.githubusercontent.com"
    __nvm_url="$__nvm_url/creationix/nvm/v0.32.0/install.sh"
    wget -q0- "$__nvm_url" | bash
fi

. "$NVM_DIR/nvm.sh"
