#! /usr/bin/env bash

declare -a __exit_callbacks

on_exit() {
    __exit_callbacks[${#__exit_callbacks[@]}]="$@"
}

prepare_exit() {
    if [ -z "$exit_code" ] ; then
        exit_code="$1"
        if [ -z "$exit_code" ] ; then
            exit_code=0
        fi
        local n
        n=${#__exit_callbacks[@]}
        for ((; n--; )) ; do
            eval "${__exit_callbacks[$n]}"
            unset __exit_callbacks[$n]
        done
    fi
}

# Don't trap SIGINT if bash is interactive
if [ -t 0 ] ; then
    __signals="TERM QUIT"
else
    __signals="INT TERM QUIT"
fi

trap "prepare_exit 1; \\exit $exit_code" $__signals
trap "prepare_exit 0; \\exit $exit_code" EXIT

unset __signals

alias exit='prepare_exit ; exit'
