#! /usr/bin/env bash

function preexec () { :; }
function preexec_invoke_exec() {
    if [ -n "$COMP_LINE" ] ; then return ; fi
    if [ "$BASH_COMMAND" '=' "$PROMPT_COMMAND" ] ; then return ; fi
    local this_command="$(
        HISTTIMEFORMAT= history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//" )";
    preexec "$this_command"
}

trap "__________=\"\$_\" ; preexec_invoke_exec ; true \"\$__________\"" DEBUG
