#! /usr/bin/env bash

if [ -z "$__prompt_guard" ] ; then __prompt_guard=1
source "$HOME/.bash-lib/init"

mload commonlib
mload colors
mload term_sequences
mload preexec

function check_sum() {
    for com in md5 md5sum shasum ; do
        if check_exit_code _ which $com ; then
            echo "$*" | "$com"
            break
        fi
    done
}

__prompt_shell_level=
__prompt_number_of_jobs=
__prompt_git_branch=
__prompt_git_remote_status=

__prompt_shell_level_flag=
__prompt_right=

function __compute_right_side_prompts() {
    __prompt_right=()
}

function __prompt_update() {
    local x=

    if [ -z "$__prompt_shell_level_flag" ] ; then
        x=
        x="${x}\[$TERM_COLORS_BOLD_BLUE\]("
        x="${x}\[$TERM_COLORS_BLUE\]$SHLVL"
        x="${x}\[$TERM_COLORS_BOLD_BLUE\])"
        x="${x}\[$TERM_COLORS_RESET\]"

        __prompt_shell_level="$x"
        __prompt_shell_level_flag=x
    fi

    __prompt_number_of_jobs=
    local x="$( echo $( jobs | wc -l | sed -e 's/ //g' ) )"
    if [ "$x" '!=' '0' ] ; then
        __prompt_number_of_jobs="($x)"
    fi

    __prompt_git_remote_status="$(
        git status --branch --porcelain --ignore-submodules=dirty 2> /dev/null |
        head -n 1 |
        grep '\[\(ahead\|behind\) [0-9]\+\]' |
        sed -e 's/^.*\(ahead\) \([0-9][0-9]*\).*$/+\2/g' |
        sed -e 's/^.*\(behind\) \([0-9][0-9]*\).*$/-\2/g'
    )"

    __prompt_git_branch="$(
        git branch 2> /dev/null |
        sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
    )"

    if [ -n "$__prompt_git_branch" ] ; then
        x=
        x="${x}git status"
        x="${x} --porcelain"
        x="${x} --ignore-submodules=dirty"

        if $x 2> /dev/null | grep -q -v '^?? .*$'; then
            __prompt_git_branch="${__prompt_git_branch}*"
        fi
    fi

    __prompt_venv="$VIRTUAL_ENV"
    if [ -n "$__prompt_venv" ] ; then
        __prompt_venv="$( basename "$__prompt_venv" )"
    fi

    subprompt=""
    botprompt=""

    date_fmt="+$TERM_COLORS_BLUE%a $TERM_COLORS_RESET%d"
    date_fmt="${date_fmt}$TERM_COLORS_RESET"
    subprompt="${subprompt}$( date "$date_fmt" )"

    subprompt="${subprompt} $TERM_COLORS_CYAN$USER"
    subprompt="${subprompt}$TERM_COLORS_BOLD_BLUE@"
    subprompt="${subprompt}$TERM_COLORS_BLUE$( hostname )"
    subprompt="${subprompt}$TERM_COLORS_RESET"

    if [ "$( pwd )" '!=' "$HOME" ] ; then
        subprompt="${subprompt} $TERM_COLORS_BOLD_GREEN["
        subprompt="${subprompt}$TERM_COLORS_GREEN$( basename "$( pwd )" )"
        subprompt="${subprompt}$TERM_COLORS_BOLD_GREEN]"
        subprompt="${subprompt}$TERM_COLORS_RESET"
    fi

    if [ -n "$__prompt_git_branch" ] ; then
        subprompt="${subprompt} $TERM_COLORS_BOLD_RED("
        subprompt="${subprompt}$TERM_COLORS_RED$__prompt_git_branch"

        if [ -n "$__prompt_git_remote_status" ] ; then
            subprompt="${subprompt}: "
            subprompt="${subprompt}$TERM_COLORS_YELLOW"
            subprompt="${subprompt}${__prompt_git_remote_status::1}"
            subprompt="${subprompt}$TERM_COLORS_BOLD_YELLOW"
            subprompt="${subprompt}${__prompt_git_remote_status:1}"
        fi

        subprompt="${subprompt}$TERM_COLORS_BOLD_RED)"
        subprompt="${subprompt}$TERM_COLORS_RESET"
    fi

    if [ -n "$__prompt_venv" ] ; then
        subprompt="${subprompt} $TERM_COLORS_BOLD_CYAN(\$"
        subprompt="${subprompt}$TERM_COLORS_CYAN"
        subprompt="${subprompt}$__prompt_venv"
        subprompt="${subprompt}$TERM_COLORS_BOLD_CYAN)"
        subprompt="${subprompt}$TERM_COLORS_RESET"
    fi

    botprompt="$( pwd )"


    term_clear_to_end

    term_cursor_save
    term_cursor_last_line
    term_clear_right
    echo -n "$botprompt"
    term_cursor_restore

    term_cursor_save
    term_cursor_down
    echo -n "$subprompt"
    term_cursor_restore

    # PS1="${PS1}$__prompt_shell_level"
    # PS1="${PS1}$__prompt_number_of_jobs"

    PS1=""
    PS1="\\[$TERM_COLORS_BOLD_RED\\]"
    PS1="${PS1}\\[$( echo -e '\xce' )\\]"
    PS1="${PS1}$( echo -e '\x94' )"
    PS1="${PS1}\\[$TERM_COLORS_RESET\\] "

    if [ "$USER" '=' 'root' ] ; then
        PS1=""
        PS1="${PS1}\\[$TERM_COLORS_RESET\\]"
        PS1="${PS1}\\[$( echo -e '\x1b[1;7;31m' )\\]"
        PS1="${PS1}\\[$( echo -e '\xc2' )\\]"
        PS1="${PS1}$( echo -e '\xae' )"
        PS1="${PS1}\\[$TERM_COLORS_RESET\\] "
        PS1="${PS1}\\[$( echo -e '\x1b[1;5;7;31m' )\\]"
        PS1="${PS1}\\[$TERM_COLORS_BOLD_RED\\]"
    fi
}

export PROMPT_COMMAND=__prompt_update

preexec() {
    echo -n "$TERM_COLORS_RESET"
    term_clear_to_end
}

fi #!__prompt_guard

