#!/usr/bin/env bash

ss() {
    (
        tmux list-sessions -F \
            '#S|#{session_windows}|#{?session_attached,*,}' \
                2>/dev/null
    ) | awk -F \| '
        BEGIN {
            extra="";
        }

        NF!=3 {
            extra = extra""$0;
        }

        NF==3 {
            com="echo "extra""$1" | base64 -d";
            extra="";
            com | getline result;
            close(com);
            print $3"|"result"|"$2;
        }' | sort | awk -F \| '{ print $1"|"$3"|"$2 }' | column -t -R 2 -s \|
    return $?
}

s() {
    local dir="$1"

    if [ -z "$dir" ] ; then
        dir="$( pwd )"
    elif [ '!' -d "$dir" ] ; then
        cd "$dir"
        return $?
    else
        dir="$( cd "$dir" && pwd )"
    fi

    name="$( echo "$dir" | base64 )"

    if [ -z "$TMUX" ] ; then
        (
            while true ; do
                display_name="$( echo "$name" | base64 -d )"
                if [ "${#display_name}" -gt 20 ] ; then
                    n="$(( ${#display_name} - 17 ))"
                    display_name="...${display_name:$n}"
                fi

                export TMUX_SESSION_DISPLAY_NAME="$display_name"
                tmux new-session -c "$dir" -d -s "$name" &> /dev/null
                tmux attach-session -d -t "$name" &> /dev/null

                if [ '!' -f "$HOME/.tmux-$name" ] ; then
                    break
                fi

                unset dir
                unset parent
                source "$HOME/.tmux-$name"
                rm -f "$HOME/.tmux-$name"

                name="$parent"
                cd "$dir"
            done
        )

    else
        current_name="$( tmux display-message -p "#S" )"
        if [ "$name" '=' "$current_name" ] ; then
            echo "Already in session"
            return 0
        fi

        if [ -z "$current_name" ] ; then
            ss
            return $?
        fi

        (
            echo "parent=\"$name\""
            echo "dir=\"$( pwd )\""
        ) > "$HOME/.tmux-$current_name"

        tmux detach-client
    fi
}
