#! /usr/bin/env bash

if [ -z "$__tab_complete_guard" ] ; then __tab_complete_guard=1
source "$HOME/.bash-lib/init"

mload commonlib

if ! shopt -oq posix; then
    envappend tc_path "/usr/share/bash-completion"
    envappend tc_path "/etc"

    searchpath tc_path bash_completion | while read tc ; do
        if [ -n "$tc" ] ; then
            source "$tc"
        fi
    done

    unset tc
    unset tc_path
fi

fi #!__tab_complete_guard

