#! /usr/bin/env bash

if [ -z "$__tmp_dir_guard" ] ; then __tmp_dir_guard=1
source "$HOME/.bash-lib/init"

mload on_exit

declare -a __tmp_dirs

__clean_tmp_dirs() {
    local n
    n=${#__tmp_dirs[@]}
    for ((; n--; )) ; do
        rm -rf "${__tmp_dirs[$n]}"
    done
}

tmp_dir() {
    local n
    n=${#__tmp_dirs[@]}

    if [ "$n" '=' '0' ] ; then
        on_exit __clean_tmp_dirs
    fi

    var="$1" ; shift

    # NOTE(opadron): need to do this in two separate ifs to avoid an indirect
    #                expansion with an empty variable
    if [ -n "$var" ] ; then
        if [ -n "${!var}" ] ; then
            return
        fi
    fi

    tmpdir="$( mktemp -d )"
    __tmp_dirs[${#tmp_dirs[@]}]="$tmpdir"

    if [ -n "$var" ] ; then
        eval "$var=\"$tmpdir\""
    else
        echo "$tmpdir"
    fi
}

fi #!__tmp_dir_guard
