#!/usr/bin/env python

import sys

import fdb

with fdb.connect(sys.argv[1]) as db:
    with db() as cur:
        account = None
        a = sys.argv[2:]
        if len(sys.argv) > 2:
            account = sys.argv[2]
            if account.startswith('-'):
                account = None
            else:
                a = a[1:]

        tbl, headers = fdb.create_bsheet_temp(
            cur, account, fdb.parse_time_spec(a)
        )

        cur.execute('SELECT * FROM {tbl}'.format(tbl=tbl))
        print fdb.format_rows(cur, headers)

