#!/usr/bin/env python

import sys
import itertools as it

import fdb

with fdb.connect(sys.argv[1]) as db:
    with db() as cur:
        args = [cur]
        if len(sys.argv) > 2: args.append(sys.argv[2])

        tbl, headers = fdb.create_bsheet_temp(*args)
        cur.execute('SELECT * FROM {tbl}'.format(tbl=tbl))
        print fdb.format_rows(cur, headers)

