#!/usr/bin/env python

import sys
import itertools as it

import fdb

with fdb.connect(sys.argv[1]) as db:
    with db() as cur:
        fdb.create_ledger_temp(cur)

        cur.execute('''
            SELECT
                date     AS "Date",
                tran     AS "Transaction",
                src      AS "From",
                dst      AS "To",
                amt_disp AS "Amount",
                com      AS "Commodity"

            FROM ledger_temp
        ''')

        print fdb.format_rows(
            cur, 'Date Transaction From To Amount Commodity'.split()
        )

        cur.execute('DROP TABLE ledger_temp')
        
