#!/usr/bin/env python

import sys
import itertools as it

import fdb

with fdb.connect(sys.argv[1]) as db:
    with db() as cur:
        tbl, headers = fdb.create_summary_temp(cur)

        query = 'SELECT * FROM {tbl}'.format(tbl=tbl)
        if len(sys.argv) > 2:
            cur.execute('''
                SELECT path FROM accounts
                WHERE code = ? OR path = ?
            ''', (sys.argv[2], sys.argv[2]))

            account = cur.fetchone()[0]

            print account

            query = ' '.join((
                query,
                'WHERE path = "{account}" OR path LIKE "{account}%"'.format(
                    account=account
                )
            ))

        cur.execute(query)
        print fdb.format_rows(( x[1:] for x in cur ), headers)

