#!/usr/bin/env python

import sys
import itertools as it

import fdb

with fdb.connect(sys.argv[1]) as db:
    with db() as cur:
        a = sys.argv[2:]

        account = None
        if len(sys.argv) > 2:
            account = sys.argv[2]
            if account.startswith('-'):
                account = None
            else:
                a = a[1:]

        tbl, headers = fdb.create_summary_temp(cur, fdb.parse_time_spec(a))
        query = 'SELECT * FROM {tbl}'.format(tbl=tbl)

        if account is not None:
            cur.execute('''
                SELECT path FROM accounts
                WHERE code = ? OR path = ?
            ''', (account, account))

            account = cur.fetchone()[0]

            query = ' '.join((
                query,
                'WHERE path = "{account}" OR path LIKE "{account}%"'.format(
                    account=account
                )
            ))

        cur.execute(query)
        print fdb.format_rows(( x[1:] for x in cur ), headers)

