#!/usr/bin/env bash

if [ -z "$TMUX" ] ; then
    name="$1"
    if [ -z "$name" ] ; then
        name=default
    fi

    tmux new-session -d -s "$name" &> /dev/null
    tmux attach-session -d -t "$name"
else
    tmux list-sessions
fi

