#!/usr/bin/env bash

if [ -n "$*" ] ; then
    eval "screen $*"
else
    if [ -z "$STY" ] ; then
        name="$1" ; if [ -z "$name" ] ; then name=default; fi
        screen -D -R -S "$name"
    else
        screen -ls
    fi
fi

