#! /usr/bin/env bash

mod_import commonlib

export LOCAL="$HOME/.local"
export SCRIPTS="$HOME/.scripts"

envpush PATH              "$LOCAL/bin"
envpush PATH              "$SCRIPTS"
envpush C_INCLUDE_PATH    "$LOCAL/include"
envpush DYLD_LIBRARY_PATH "$LOCAL/lib"
envpush LD_LIBRARY_PATH   "$LOCAL/lib"
envpush LD_RUN_PATH       "$LOCAL/lib"
envpush NODE_PATH         "$LOCAL/lib/node_modules"

envpush PATH              "$LOCAL/bin"

export EDITOR='vim'
export PYTHONSTARTUP="$HOME/.pythonrc.py"

