#! /usr/bin/env bash

mod_import colors

function check_sum() {
    for com in md5 md5sum shasum ; do
        which "$com" &> /dev/null
        if [ "$?" '=' '0' ] ; then
            echo "$*" | "$com"
            break
        fi
    done
}

__prompt_shell_level=
__prompt_number_of_jobs=
__prompt_git_branch=
__prompt_git_remote_status=
__prompt_is_root=

__prompt_shell_level_flag=
__prompt_is_root_flag=

function __prompt_update() {
    local x=

    if [ -z "$__prompt_shell_level_flag" ] ; then
        x=
        x="${x}\[$TERM_COLORS_BLUE\]("
        x="${x}\[$TERM_COLORS_blue\]$SHLVL"
        x="${x}\[$TERM_COLORS_BLUE\])"
        x="${x}\[$TERM_COLORS_RESET\]"

        __prompt_shell_level="$x"
        __prompt_shell_level_flag=x
    fi

    __prompt_number_of_jobs=
    local x="$( echo $( jobs | wc -l ) )"
    if [ "$x" '!=' '0' ] ; then
        __prompt_number_of_jobs="($x)"
    fi

    __prompt_git_remote_status="$(
        git status --branch --porcelain --ignore-submodules=dirty 2> /dev/null |
        head -n 1 |
        grep '\[\(ahead\|behind\) [0-9]\+\]' |
        sed -e 's/^.*\(ahead\) \([0-9][0-9]*\).*$/+\2/g' |
        sed -e 's/^.*\(behind\) \([0-9][0-9]*\).*$/-\2/g'
    )"

    x=
    if [ -n "$__prompt_git_remote_status" ] ; then
        x="${x} "
        x="${x}\[$TERM_COLORS_YELLOW\]("
        x="${x}\[$TERM_COLORS_yellow\]$__prompt_git_remote_status"
        x="${x}\[$TERM_COLORS_YELLOW\])"
        x="${x}\[$TERM_COLORS_RESET\]"
        __prompt_git_remote_status="$x"
    fi

    __prompt_git_branch="$(
        git branch 2> /dev/null |
        sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
    )"

    if [ -n "$__prompt_git_branch" ] ; then
        x=
        x="${x}git status"
        x="${x} --porcelain"
        x="${x} --ignore-submodules=dirty"

        if $x 2> /dev/null | grep -q -v '^?? .*$'; then
            __prompt_git_branch="${__prompt_git_branch}*"
        fi

        x=
        x="${x}\[$TERM_COLORS_RESET\] "
        x="${x}\[$TERM_COLORS_RED\]("
        x="${x}\[$TERM_COLORS_red\]$__prompt_git_branch"
        x="${x}\[$TERM_COLORS_RED\])"
        x="${x}\[$TERM_COLORS_RESET\]"

        __prompt_git_branch="$x"
    fi

    if [ -z "$__prompt_is_root_flag" ] ; then
        x=
        if [ "$USER" '=' 'root' ] ; then
            x="${x}\[$( echo -e '\x1b[5;7;47m' )\]"
            x="${x}\[$TERM_COLORS_RED\]R"
            x="${x}\[$TERM_COLORS_RESET\] "
        fi

        __prompt_is_root="$x"
        __prompt_is_root_flag=x
    fi

    PS1=
    # date
    # PS1="${PS1}\\[$TERM_COLORS_blue\\]\`date '+%m'\`"
    # PS1="${PS1}\\[$TERM_COLORS_BLUE\\]\`date '+%d'\`"
    # PS1="${PS1}\\[$TERM_COLORS_RESET\\]"
    
    # time
    # PS1="${PS1}\\[$TERM_COLORS_cyan\\]\`date '+%k'\`"
    # PS1="${PS1}\\[$TERM_COLORS_CYAN\\]\`date '+%M'\`"
    # PS1="${PS1}\\[$TERM_COLORS_RESET\\]"
    
    # machine status
    # PS1="${PS1}`uname_at_host`"
    # PS1="${PS1}\\[$TERM_COLORS_RESET\\] "
    
    PS1="${PS1}$__prompt_shell_level"
    PS1="${PS1}$__prompt_number_of_jobs"
    PS1="${PS1} "
    
    PS1="${PS1}\\[$TERM_COLORS_GREEN\\]["
    PS1="${PS1}\\[$TERM_COLORS_green\\]\\W"
    
    PS1="${PS1}$__prompt_git_branch"
    PS1="${PS1}$__prompt_git_remote_status"
    
    PS1="${PS1}\\[$TERM_COLORS_GREEN\\]]"
    
    PS1="${PS1}\\[$TERM_COLORS_RESET\\] "
    PS1="${PS1}$__prompt_is_root"

}

export PROMPT_COMMAND=__prompt_update

