#! /usr/bin/env bash

mod_import commonlib

if ! shopt -oq posix; then
    envappend tc_path "/usr/share/bash-completion"
    envappend tc_path "/etc"

    searchpath tc_path bash_completion | while read tc ; do
        if [ -n "$tc" ] ; then
            source "$tc"
        fi
    done

    unset tc
    unset tc_path
fi

