#! /usr/bin/env bash

function envget() {
    while [ -n "$*" ] ; do
        local key="$1" ; shift
        eval 'echo $'"$key"
    done
}

function envset() {
    while [ -n "$*" ] ; do
        local key="$1" ; shift
        local value="$1" ; shift

        if [ -z "$value" ] ; then
            unset $key
        else
            eval "$key="'"'"$value"'"'
        fi
    done
}

function envappend() {
    local sep=':'

    local regex='[\.;:\\/, -]'
    if [[ "$1" =~ $regex ]] ; then
        sep="$1" ; shift
    fi

    local var="$1" ; shift
    local val="$1" ; shift
    while [ -n "$*" ] ; do
        val="$val$sep$1" ; shift
    done

    if [ -z "$( envget "$var" )" ] ; then
        envset "$var" "$val"
    else
        envset "$var" "$( envget "$var" )$sep$val"
    fi
}

function envpush() {
    local sep=':'

    local regex='[\.;:\\/, -]'
    if [[ "$1" =~ $regex ]] ; then
        sep="$1" ; shift
    fi

    local var="$1" ; shift
    local val="$1" ; shift
    while [ -n "$*" ] ; do
        val="$val$sep$1" ; shift
    done

    if [ -z "$( envget "$var" )" ] ; then
        envset "$var" "$val"
    else
        envset "$var" "$val$sep$( envget "$var" )"
    fi
}

realpath . &> /dev/null
if [ "$?" '!=' '0' ]; then
    function realpath() {
        python -c "$(
            echo 'import os.path as p'
            echo 'import sys'
            echo 'for arg in sys.argv[1:]:'
            echo '    print p.abspath(arg)'
        )" $*
    }
fi

function searchpath() {
    local path="$( envget $1 )" ; shift
    local file_name="$1" ; shift

    while [ -n "$path" ] ; do
        local dir="${path/:*/}"
        local ndir="${#dir}"
        path="${path:$(( ndir + 1 ))}"

        test_path="$dir/$file_name"
        if [ -f "$test_path" ] ; then
            echo "$test_path"
            return 0
        fi
    done

    return 1
}

