#! /usr/bin/env bash

function parse_git_branch() {
    echo "$(
        git branch 2> /dev/null |
        sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
    )"
}

function parse_git_branch_head() {
    if [ -n "$( parse_git_branch )" ] ; then
        echo '('
    fi
}

function parse_git_branch_tail() {
    if [ -n "$( parse_git_branch )" ] ; then
        echo ')'
    fi
}

function parse_git_branch_space() {
    if [ -n "$( parse_git_branch )" ] ; then
        echo ' '
    fi
}

function uname_at_host() {

    if [ "$USER" '=' 'root' ] ;then
        blink_fragment='5;'
    fi
    c0="\[$( echo -e '\x1b[1;'"$blink_fragment"'37;41m' )\]"
    c1="\[$( echo -e '\x1b[1;'"$blink_fragment"'37;43m' )\]"
    c2="\[$( echo -e '\x1b[1;'"$blink_fragment"'37;44m' )\]"
    c3="\[$( echo -e '\x1b[1;'"$blink_fragment"'37;45m' )\]"
    c4="\[$( echo -e '\x1b[1;'"$blink_fragment"'37;46m' )\]"

    hn="$( hostname )"
    n_ret=0
    ret=""
    csum="$hn"
    is_done=0
    while [ "$is_done" '=' '0' ] ; do
        csum="$( echo "$csum" | md5 )"
        for ((i=0; i<"${#csum}"; ++i)) ; do
            digit="$(( 0x${csum:$i:1} % 5 ))"
            code="$( eval 'echo $c'"$digit" )"

            if [ -z "$code" ] ; then
                continue
            fi

            ret="$ret$code${USER:$n_ret:1}"
            n_ret="$(( n_ret + 1 ))"

            if [ "$n_ret" '=' '4' ] ; then
                is_done=1
                break
            fi

        done
    done

    echo "$ret"
}


red="\[$( echo -e '\x1b[0;31m' )\]"
grn="\[$( echo -e '\x1b[0;32m' )\]"
blu="\[$( echo -e '\x1b[0;34m' )\]"
cyn="\[$( echo -e '\x1b[0;36m' )\]"
                            
RED="\[$( echo -e '\x1b[1;31m' )\]"
GRN="\[$( echo -e '\x1b[1;32m' )\]"
BLU="\[$( echo -e '\x1b[1;34m' )\]"
CYN="\[$( echo -e '\x1b[1;36m' )\]"

RES="\[$( echo -e '\x1b[0m' )\]"

# date
p="${p}$blu\`date '+%m'\`"
p="${p}$BLU\`date '+%d'\`"

# time
p="${p}$cyn\`date '+%k'\`"
p="${p}$CYN\`date '+%M'\`"
p="${p}$RES "

# machine status
p="${p}`uname_at_host`"
p="${p}$RES "

# cwd
p="${p}$GRN["
p="${p}$grn\\W"

# current git branch
p="${p}$RES\`parse_git_branch_space\`"
p="${p}$RED\`parse_git_branch_head\`"
p="${p}$red\`parse_git_branch\`"
p="${p}$RED\`parse_git_branch_tail\`"

p="${p}$GRN]"
p="${p}$RES "


export PS1="$p"

unset p

unset red
unset blu
unset grn
unset cyn

unset RED
unset BLU
unset GRN
unset CYN

